import { ArrowUpRight, Mail, MapPin } from "lucide-react";

const papers = [
  { venue:"ACL 2026 · Main", role:"共同一作", title:"SGPVT: Self-Generated Proximal Visual Tokens for Mitigating Collateral Damage in MLLM Unlearning", text:"在删除目标概念的同时保护语义相邻知识。提出自适应余弦图像扰动与双流对抗训练，在 LLaVA-1.5 / 13B 上将近端概念保留准确率提升 3–5%。", tags:["MLLM Unlearning","Knowledge Retention","Benchmark"], href:"https://aclanthology.org/2026.acl-long.442.pdf", link:"ACL Anthology" },
  { venue:"KDD 2027 · Under Review", role:"第一作者", title:"What to Edit Next: Visually Grounded Follow-up Recommendation for Image Editing", text:"构建图像编辑追问推荐的 SFT—奖励建模—多目标 GRPO 链路，并设计源—目标视觉校验器。系统已上线千问 App，14 天 A/B 中 CTR +32.70%。", tags:["Visual Alignment","Recommendation","GRPO"] },
  { venue:"AAAI 2026 · Under Review", role:"第一作者", title:"SPACE: Source-Free Concept Unlearning for Multimodal Large Language Models", text:"面向无法访问目标视觉数据的隐私场景，提出基于代理的间接遗忘范式，通过 TPAS 检索语义锚点，并以 DCSI 约束更新方向。", tags:["Source-free","Machine Unlearning","Privacy"], href:"https://arxiv.org/abs/2606.09868", link:"arXiv" },
];

const jobs = [
  ["2026.08 — 至今","蚂蚁 · 百灵基座大模型","基座后训练算法实习生 · Agentic RL","参与基座模型 Agent 能力后训练与强化学习对齐，覆盖 40K+ SFT 轨迹、sandbox rollout、过程与结果奖励联合优化。内部评测中工具调用 F1 提升 10+ 点，复杂任务成功率提升 8+ 点。"],
  ["2026.03 — 至今","阿里巴巴 · 千问事业群","多模态后训练算法实习生","负责 Qwen3-VL-8B 图像编辑追问推荐从数据构建、后训练到上线评估的全链路。基于 173K 位置感知偏好对训练奖励模型，视觉不一致率由 3.7% 降至 0.9%。"],
  ["2025.02 — 2025.07","科大讯飞 · 洛阳研究院","多模态大模型算法实习生","构建覆盖 70+ 疾病的多模态指令数据并完成垂域微调，将智慧养殖疾病召回率由 33% 提升至 74%，方案面向中粮集团完成业务试点。"],
  ["2024.07 — 2025.01","华为上海研究所 · 无线网络产品线","大模型应用算法实习生 · 代码智能 Agent","参与百万行级代码库的需求解析、RAG 检索、代码生成与静态校验链路，多 Agent 系统批量检出高危缺陷并被内部质检平台采纳。"],
];

export default function Home(){return <main>
  <header className="site-header"><a className="wordmark" href="#top">张芷境 <span>/ ZJ</span></a><nav><a href="#research">研究</a><a href="#experience">经历</a><a href="#projects">项目</a><a href="#contact">联系</a></nav><a className="header-mail" href="mailto:1213760905@qq.com">Email <ArrowUpRight size={14}/></a></header>
  <section className="hero" id="top"><div className="kicker"><span/> MULTIMODAL AI · POST-TRAINING · ALIGNMENT</div><h1>让多模态模型<br/><em>学会，也懂得忘记。</em></h1><div className="hero-bottom"><p className="intro">我是张芷境，东南大学计算机技术硕士研究生。我的研究聚焦于多模态大模型的后训练、对齐与机器遗忘，关注模型能力、可靠性与真实应用之间的连接。</p><div className="hero-meta"><p><MapPin size={16}/> 南京，中国</p><p className="status"><span/> Open to research collaborations</p></div></div><div className="orbit" aria-hidden="true"><span>MLLM</span></div></section>
  <section className="metrics"><div><strong>03</strong><span>Selected papers</span></div><div><strong>02</strong><span>First-author works</span></div><div><strong>4+</strong><span>Industry labs</span></div><div><strong>10M+</strong><span>Users reached</span></div></section>
  <section className="section" id="research"><div className="section-label"><span>01</span><p>SELECTED RESEARCH</p></div><div className="section-content"><div className="section-heading"><h2>研究工作</h2><p>围绕多模态模型的知识边界、视觉对齐与可信后训练展开。</p></div><div className="paper-list">{papers.map((p,i)=><article className="paper" key={p.title}><div className="paper-index">0{i+1}</div><div className="paper-body"><div className="paper-meta"><span>{p.venue}</span><span>{p.role}</span></div><h3>{p.title}</h3><p>{p.text}</p><div className="paper-footer"><div>{p.tags.map(t=><span key={t}>{t}</span>)}</div>{p.href&&<a href={p.href} target="_blank" rel="noreferrer">{p.link}<ArrowUpRight size={15}/></a>}</div></div></article>)}</div></div></section>
  <section className="section experience-section" id="experience"><div className="section-label"><span>02</span><p>EXPERIENCE</p></div><div className="section-content"><div className="section-heading"><h2>产业研究经历</h2><p>把研究方法带入真实、复杂且规模化的模型系统。</p></div><div className="timeline">{jobs.map(j=><article key={j[1]}><time>{j[0]}</time><div><h3>{j[1]}</h3><h4>{j[2]}</h4><p>{j[3]}</p></div></article>)}</div></div></section>
  <section className="feature" id="projects"><div className="feature-top"><span>FEATURED PROJECT · 2023—2025</span><span>CORE ALGORITHM LEAD</span></div><div className="feature-grid"><div><p className="kicker">MONTAGE AI</p><h2>从热点到成片的<br/>全流程内容生产 Agent</h2></div><div className="feature-copy"><p>主导设计“热点追踪—文案生成—素材收集—素材匹配—内容裂变”自动化链路，并提出 Vitex 视频形式化描述体系。</p><div className="feature-numbers"><p><strong>82%</strong><span>语义匹配准确率</span></p><p><strong>300+</strong><span>日均自动化视频</span></p><p><strong>−60%</strong><span>内容制作成本</span></p></div></div></div><p className="award-note">国家级一等奖 · 全球校园人工智能算法精英大赛</p></section>
  <section className="education section"><div className="section-label"><span>03</span><p>EDUCATION & HONORS</p></div><div className="section-content edu-grid"><div><h2>东南大学</h2><p>计算机技术 · 硕士（推免）</p><time>2025.09 — 2028.06</time><p className="degree">软件工程 · 学士</p><time>2021.09 — 2025.06</time></div><ul><li><span>2025</span>东南大学一等学业奖学金</li><li><span>2024</span>东南大学至善奖学金</li><li><span>2023</span>全球校园人工智能算法精英大赛 · 国家一等奖</li></ul></div></section>
  <footer id="contact"><p className="kicker">LET’S CONNECT</p><h2>对研究合作、模型对齐<br/>或有意思的想法感兴趣？</h2><a href="mailto:1213760905@qq.com"><Mail size={19}/> 1213760905@qq.com <ArrowUpRight size={18}/></a><div className="footer-bottom"><span>张芷境 · Academic Homepage</span><span>Built with curiosity in Nanjing.</span></div></footer>
</main>}
